clc;
close all;
[y,Fs]=audioread('16.wav');
siglength=length(y);
T=1/Fs;
t=(1:siglength)*T;
subplot(2,2,1);
plot(t,y);
title('原始信号时域图');
xlabel('时间/s');
ylabel('声音信号');
Y=fft(y,20000);
K=length(20*log10(abs(Y)));
f=-pi:2*pi/(K-1):pi;
subplot(2,2,2);
plot(f,20*log10(abs(Y)));
title('原始信号频谱');
xlabel('信号频率');
ylabel('信号幅值');
[y1,Fs]=audioread('16noise.wav');
t1=(1:length(y1))*T;
subplot(2,2,3);
plot(t1,y1);
title('含噪声信号时域图');
xlabel('时间/s');
ylabel('声音信号');
Y2=abs(fft(y1));
P=length(20*log10(abs(Y2)));
f1=-pi:2*pi/(P-1):pi;
subplot(2,2,4);
plot(f1,20*log10(abs(Y2)));
title('含噪声信号频域图');
xlabel('信号频率');
ylabel('信号幅值');

%2倍内插
N=20000;
n=0:0.5:N-1;
[x,Fs]=audioread('16.wav');
len=length(x);
len1=2*len;
slow=zeros(1,len1);
for(i=1:len)
    slow(2*i-1)=0;
    slow(2*i)=x(i);
end
SLOW=fft(slow,20000);%显示内插后信号频谱
K=length(20*log10(abs(SLOW)));
f1=-pi:2*pi/(K-1):pi;
figure
subplot(2,2,2);
plot(f1,20*log10(abs(SLOW)));
title('原始信号频谱');
xlabel('信号频率');
ylabel('信号幅值');

n=[-1000:1000];%低通滤波
x=sin(1*n)./(pi*n);
x(1001)=1/pi;
z=conv(x,slow);
N=length(z);
Z=fftshift(fft(z,N));
w=linspace(-pi,pi,N);
plot(w,20*log10(abs(Z)));
sound(z,Fs);

%5倍抽取
N=100;
n=0:1:N-1;
[x,Fs]=audioread('16.wav');
y=zeros(1,length(x));
for i=1:5:length(x);
   y(i)=x(i);
end
QUICK=fft(y,20000);
K1=length(20*log10(abs(QUICK)));
f1=-pi:2*pi/(K1-1):pi;
subplot(2,2,2);
plot(f1,20*log10(abs(QUICK)));
title('原始信号频谱');
xlabel('信号频率');
ylabel('信号幅值');
sound(y,Fs);